spring:
  application:
    name: selsolun-back

  # Configuration de la source de donn?es MySQL
  datasource:
      url: ${DATA_URL:jdbc:mysql://192.168.1.101:3306/crypto_app}
      username: ${DATA_USERNAME:root}
      password: ${DATE_PASSWORD:root_password}
      driver-class-name: com.mysql.cj.jdbc.Driver

  # Configuration de JPA (Java Persistence API)
  jpa:
      hibernate.ddl-auto: update
      show-sql: false
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          format_sql: true
